basePath: /api/v1
definitions:
  models.ColonyList:
    properties:
      population_list:
        example:
        - 0
        items:
          type: integer
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /ant:
    get:
      consumes:
      - text/plain
      description: get collonies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ColonyList'
        "400":
          description: ssd
      summary: List Collonies population
      tags:
      - ant
swagger: "2.0"
